import { type NodeType } from "../../types/diagrams";

type NodeStyle = { bg: string; border: string; icon: string };

const style = (color: string): NodeStyle => ({
  bg: `bg-${color}-100/20`,
  border: `border-${color}-300/50`,
  icon: `text-${color}-600`,
});

const hslStyle = (hsl: string): NodeStyle => ({
  bg: `bg-[hsl(${hsl}/0.15)]`,
  border: `border-[hsl(${hsl}/0.5)]`,
  icon: `text-[hsl(${hsl})]`,
});

const awsStyle = style("orange");
const azureStyle = style("cyan");
const animatedStyle = style("violet");
const gcpBlueStyle = style("blue");
const gcpRedStyle = style("red");

export const nodeTypeStyles: Record<NodeType, NodeStyle> = {
  service: hslStyle("187_72%_50%"),
  database: hslStyle("262_83%_58%"),
  server: hslStyle("142_71%_45%"),
  client: hslStyle("38_92%_50%"),
  storage: hslStyle("346_77%_50%"),
  api: hslStyle("199_89%_48%"),
  text: { bg: "bg-transparent", border: "border-transparent", icon: "text-foreground" },
  group: { bg: "bg-secondary/30", border: "border-border border-dashed", icon: "text-muted-foreground" },
  "process-requirements": style("indigo"),
  "process-design": style("violet"),
  "process-development": style("sky"),
  "process-testing": style("amber"),
  "process-deployment": style("emerald"),
  "process-monitoring": style("rose"),
  "gcp-cloud-run": gcpBlueStyle,
  "gcp-cloud-storage": gcpRedStyle,
  "gcp-bigquery": gcpBlueStyle,
  "gcp-pub-sub": style("yellow"),
  "gcp-apigee": gcpBlueStyle,
  "gcp-billing": style("green"),
  "gcp-cloud-build": gcpBlueStyle,
  "gcp-cloud-monitoring": gcpRedStyle,
  "gcp-cloud-sql": style("orange"),
  "gcp-compute-engine": gcpBlueStyle,
  "gcp-iam": style("purple"),
  "gcp-kubernetes": gcpBlueStyle,
  "gcp-security": gcpRedStyle,
  "aws-ec2": awsStyle,
  "aws-s3": awsStyle,
  "aws-lambda": awsStyle,
  "aws-rds": awsStyle,
  "aws-eks": awsStyle,
  "aws-cloudwatch": awsStyle,
  "aws-iam": awsStyle,
  "aws-api-gateway": awsStyle,
  "aws-codebuild": awsStyle,
  "aws-codepipeline": awsStyle,
  "aws-sqs": awsStyle,
  "aws-sns": awsStyle,
  "aws-dynamodb": awsStyle,
  "aws-cloudfront": awsStyle,
  "aws-fargate": awsStyle,
  "azure-vm": azureStyle,
  "azure-blob-storage": azureStyle,
  "azure-functions": azureStyle,
  "azure-sql-database": azureStyle,
  "azure-aks": azureStyle,
  "azure-monitor": azureStyle,
  "azure-entra-id": azureStyle,
  "azure-api-management": azureStyle,
  "azure-devops": azureStyle,
  "azure-service-bus": azureStyle,
  "azure-event-grid": azureStyle,
  "azure-cosmos-db": azureStyle,
  "azure-container-apps": azureStyle,
  "azure-key-vault": azureStyle,
  "nosql-mongodb": style("green"),
  "nosql-redis": style("red"),
  "nosql-cassandra": style("blue"),
  "nosql-couchdb": style("red"),
  "nosql-firebase": style("amber"),
  "nosql-influxdb": style("purple"),
  "nosql-rocksdb": style("slate"),
  "sql-mysql": style("blue"),
  "sql-postgresql": style("sky"),
  "sql-sqlite": style("blue"),
  "sql-oracle": style("red"),
  "sql-mssql": style("red"),
  "sql-sqlalchemy": style("orange"),
  "shape-circle": style("pink"),
  "shape-square": style("blue"),
  "shape-star": style("yellow"),
  "shape-hexagon": style("teal"),
  "animated-api": animatedStyle,
  "animated-click": animatedStyle,
  "animated-cloud": animatedStyle,
  "animated-double-check": animatedStyle,
  "animated-loading-bubble": animatedStyle,
  "animated-loading": animatedStyle,
  "animated-rocket": animatedStyle,
  "animated-settings": animatedStyle,
  "animated-target": animatedStyle,
  "animated-upload-cloud": animatedStyle,
  "animated-upload": animatedStyle,
  "animated-verified": animatedStyle,
  "animated-worker": animatedStyle,
};
