import { type NodeType } from "../../types/diagrams";

type NodeStyle = { bg: string; border: string; icon: string };

// Tailwind JIT requires full class names to be statically present in source.
// Do NOT use dynamic class construction like `bg-${color}-100/20`.

const awsStyle: NodeStyle = { bg: "bg-orange-100/20", border: "border-orange-300/50", icon: "text-orange-600" };
const azureStyle: NodeStyle = { bg: "bg-cyan-100/20", border: "border-cyan-300/50", icon: "text-cyan-600" };
const animatedStyle: NodeStyle = { bg: "bg-violet-100/20", border: "border-violet-300/50", icon: "text-violet-600" };
const gcpBlueStyle: NodeStyle = { bg: "bg-blue-100/20", border: "border-blue-300/50", icon: "text-blue-600" };
const gcpRedStyle: NodeStyle = { bg: "bg-red-100/20", border: "border-red-300/50", icon: "text-red-600" };

export const nodeTypeStyles: Record<NodeType, NodeStyle> = {
  service: { bg: "bg-[hsl(187_72%_50%/0.15)]", border: "border-[hsl(187_72%_50%/0.5)]", icon: "text-[hsl(187_72%_50%)]" },
  database: { bg: "bg-[hsl(262_83%_58%/0.15)]", border: "border-[hsl(262_83%_58%/0.5)]", icon: "text-[hsl(262_83%_58%)]" },
  server: { bg: "bg-[hsl(142_71%_45%/0.15)]", border: "border-[hsl(142_71%_45%/0.5)]", icon: "text-[hsl(142_71%_45%)]" },
  client: { bg: "bg-[hsl(38_92%_50%/0.15)]", border: "border-[hsl(38_92%_50%/0.5)]", icon: "text-[hsl(38_92%_50%)]" },
  storage: { bg: "bg-[hsl(346_77%_50%/0.15)]", border: "border-[hsl(346_77%_50%/0.5)]", icon: "text-[hsl(346_77%_50%)]" },
  api: { bg: "bg-[hsl(199_89%_48%/0.15)]", border: "border-[hsl(199_89%_48%/0.5)]", icon: "text-[hsl(199_89%_48%)]" },
  text: { bg: "bg-transparent", border: "border-transparent", icon: "text-foreground" },
  group: { bg: "bg-secondary/30", border: "border-border border-dashed", icon: "text-muted-foreground" },
  "process-requirements": { bg: "bg-indigo-100/20", border: "border-indigo-300/50", icon: "text-indigo-600" },
  "process-design": { bg: "bg-violet-100/20", border: "border-violet-300/50", icon: "text-violet-600" },
  "process-development": { bg: "bg-sky-100/20", border: "border-sky-300/50", icon: "text-sky-600" },
  "process-testing": { bg: "bg-amber-100/20", border: "border-amber-300/50", icon: "text-amber-600" },
  "process-deployment": { bg: "bg-emerald-100/20", border: "border-emerald-300/50", icon: "text-emerald-600" },
  "process-monitoring": { bg: "bg-rose-100/20", border: "border-rose-300/50", icon: "text-rose-600" },
  "gcp-cloud-run": gcpBlueStyle,
  "gcp-cloud-storage": gcpRedStyle,
  "gcp-bigquery": gcpBlueStyle,
  "gcp-pub-sub": { bg: "bg-yellow-100/20", border: "border-yellow-300/50", icon: "text-yellow-600" },
  "gcp-apigee": gcpBlueStyle,
  "gcp-billing": { bg: "bg-green-100/20", border: "border-green-300/50", icon: "text-green-600" },
  "gcp-cloud-build": gcpBlueStyle,
  "gcp-cloud-monitoring": gcpRedStyle,
  "gcp-cloud-sql": { bg: "bg-orange-100/20", border: "border-orange-300/50", icon: "text-orange-600" },
  "gcp-compute-engine": gcpBlueStyle,
  "gcp-iam": { bg: "bg-purple-100/20", border: "border-purple-300/50", icon: "text-purple-600" },
  "gcp-kubernetes": gcpBlueStyle,
  "gcp-security": gcpRedStyle,
  "aws-ec2": awsStyle,
  "aws-s3": awsStyle,
  "aws-lambda": awsStyle,
  "aws-rds": awsStyle,
  "aws-eks": awsStyle,
  "aws-cloudwatch": awsStyle,
  "aws-iam": awsStyle,
  "aws-api-gateway": awsStyle,
  "aws-codebuild": awsStyle,
  "aws-codepipeline": awsStyle,
  "aws-sqs": awsStyle,
  "aws-sns": awsStyle,
  "aws-dynamodb": awsStyle,
  "aws-cloudfront": awsStyle,
  "aws-fargate": awsStyle,
  "azure-vm": azureStyle,
  "azure-blob-storage": azureStyle,
  "azure-functions": azureStyle,
  "azure-sql-database": azureStyle,
  "azure-aks": azureStyle,
  "azure-monitor": azureStyle,
  "azure-entra-id": azureStyle,
  "azure-api-management": azureStyle,
  "azure-devops": azureStyle,
  "azure-service-bus": azureStyle,
  "azure-event-grid": azureStyle,
  "azure-cosmos-db": azureStyle,
  "azure-container-apps": azureStyle,
  "azure-key-vault": azureStyle,
  "nosql-mongodb": { bg: "bg-green-100/20", border: "border-green-300/50", icon: "text-green-600" },
  "nosql-redis": { bg: "bg-red-100/20", border: "border-red-300/50", icon: "text-red-600" },
  "nosql-cassandra": { bg: "bg-blue-100/20", border: "border-blue-300/50", icon: "text-blue-600" },
  "nosql-couchdb": { bg: "bg-red-100/20", border: "border-red-300/50", icon: "text-red-600" },
  "nosql-firebase": { bg: "bg-amber-100/20", border: "border-amber-300/50", icon: "text-amber-600" },
  "nosql-influxdb": { bg: "bg-purple-100/20", border: "border-purple-300/50", icon: "text-purple-600" },
  "nosql-rocksdb": { bg: "bg-slate-100/20", border: "border-slate-300/50", icon: "text-slate-600" },
  "sql-mysql": { bg: "bg-blue-100/20", border: "border-blue-300/50", icon: "text-blue-600" },
  "sql-postgresql": { bg: "bg-sky-100/20", border: "border-sky-300/50", icon: "text-sky-600" },
  "sql-sqlite": { bg: "bg-blue-100/20", border: "border-blue-300/50", icon: "text-blue-600" },
  "sql-oracle": { bg: "bg-red-100/20", border: "border-red-300/50", icon: "text-red-600" },
  "sql-mssql": { bg: "bg-red-100/20", border: "border-red-300/50", icon: "text-red-600" },
  "sql-sqlalchemy": { bg: "bg-orange-100/20", border: "border-orange-300/50", icon: "text-orange-600" },
  "shape-circle": { bg: "bg-pink-100/20", border: "border-pink-300/50", icon: "text-pink-600" },
  "shape-square": { bg: "bg-blue-100/20", border: "border-blue-300/50", icon: "text-blue-600" },
  "shape-star": { bg: "bg-yellow-100/20", border: "border-yellow-300/50", icon: "text-yellow-600" },
  "shape-hexagon": { bg: "bg-teal-100/20", border: "border-teal-300/50", icon: "text-teal-600" },
  "animated-api": animatedStyle,
  "animated-click": animatedStyle,
  "animated-cloud": animatedStyle,
  "animated-double-check": animatedStyle,
  "animated-loading-bubble": animatedStyle,
  "animated-loading": animatedStyle,
  "animated-rocket": animatedStyle,
  "animated-settings": animatedStyle,
  "animated-target": animatedStyle,
  "animated-upload-cloud": animatedStyle,
  "animated-upload": animatedStyle,
  "animated-verified": animatedStyle,
  "animated-worker": animatedStyle,
};
